# Generated by Django 5.0.2 on 2024-04-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CMS", "0003_rename_raw_material_rawmaterial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "product_id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=30)),
                ("category", models.CharField(max_length=2)),
            ],
            options={
                "db_table": "product",
            },
        ),
    ]
