# Generated by Django 5.0.2 on 2024-04-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CMS", "0004_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stage",
            field=models.CharField(default="", max_length=3),
        ),
    ]
