# Generated by Django 5.0.2 on 2024-04-22 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CMS", "0006_alter_product_stage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "product_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="CMS.product",
                        verbose_name="product",
                    ),
                ),
                ("operation", models.CharField(max_length=5)),
                ("number", models.IntegerField(max_length=8)),
                ("unit", models.CharField(max_length=5)),
                ("data_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "Inventory",
            },
        ),
    ]
