# Generated by Django 5.0.2 on 2024-04-22 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CMS", "0008_alter_inventory_product_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventory",
            options={"ordering": ["product_id"]},
        ),
    ]
