# Generated by Django 5.0.2 on 2024-04-22 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CMS", "0009_alter_inventory_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventory",
            options={},
        ),
    ]
