# Generated by Django 5.0.2 on 2024-04-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CMS", "0011_inventory_record_alter_inventory_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="record",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
