# Generated by Django 5.0.2 on 2024-04-23 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CMS", "0012_alter_inventory_record"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="product_id",
            field=models.ForeignKey(
                db_column="product_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="CMS.product",
                verbose_name="product",
            ),
        ),
    ]
