# Generated by Django 5.0.2 on 2024-03-11 07:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("developer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="developer",
            name="name",
        ),
    ]
