# Generated by Django 5.0.2 on 2024-04-02 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HRM", "0006_remove_hr_level"),
        ("developer", "0002_remove_developer_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="developer",
            name="manager",
        ),
        migrations.AlterField(
            model_name="developer",
            name="dev_id",
            field=models.ForeignKey(
                db_column="dev_id",
                limit_choices_to={"departments": "IT"},
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="dev_id",
                serialize=False,
                to="HRM.staff",
            ),
        ),
    ]
