# Generated by Django 5.0.2 on 2024-03-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HR",
            fields=[
                (
                    "hr_id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=20)),
                ("manager", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "HR",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "staff_id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=20)),
                ("en_name", models.CharField(max_length=20)),
                ("departments", models.CharField(max_length=5)),
                ("level", models.CharField(max_length=1)),
                ("on_the_job", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "staff",
            },
        ),
    ]
