# Generated by Django 5.0.2 on 2024-04-01 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HRM", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealSupplier",
            fields=[
                ("ms_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=10)),
                ("contact_person", models.CharField(max_length=10)),
                ("contact_person_phone", models.CharField(max_length=10)),
                ("meal_time", models.CharField(max_length=5)),
                ("take_way", models.CharField(max_length=2)),
                ("score", models.FloatField()),
            ],
            options={
                "db_table": "meal_supplier",
            },
        ),
        migrations.AlterField(
            model_name="hr",
            name="hr_id",
            field=models.ForeignKey(
                limit_choices_to={"departments": "HR"},
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="HRM.staff",
            ),
        ),
    ]
