# Generated by Django 5.0.2 on 2024-04-01 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HRM", "0002_mealsupplier_alter_hr_hr_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hr",
            name="hr_id",
            field=models.ForeignKey(
                db_column="hr_id",
                limit_choices_to={"departments": "HR"},
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="HRM.staff",
            ),
        ),
    ]
