# Generated by Django 5.0.2 on 2024-04-01 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HRM", "0003_alter_hr_hr_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hr",
            name="manager",
        ),
        migrations.AddField(
            model_name="hr",
            name="level",
            field=models.ForeignKey(
                db_column="level",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hr_level",
                to="HRM.staff",
            ),
        ),
        migrations.AlterField(
            model_name="hr",
            name="hr_id",
            field=models.ForeignKey(
                db_column="hr_id",
                limit_choices_to={"departments": "HR"},
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="hr_id",
                serialize=False,
                to="HRM.staff",
            ),
        ),
    ]
