# Generated by Django 5.0.2 on 2024-04-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HRM", "0004_remove_hr_manager_hr_level_alter_hr_hr_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hr",
            name="level",
            field=models.CharField(max_length=1, null=True),
        ),
    ]
