# Generated by Django 5.0.2 on 2024-04-02 04:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("HRM", "0005_alter_hr_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hr",
            name="level",
        ),
    ]
